INSERT INTO employees(name,last_name) VALUES("sebastian","suarez");
INSERT INTO employees(name,last_name) VALUES("pepe","gutierrez");
INSERT INTO employees(name,last_name) VALUES("juan","hernandez");
INSERT INTO employees(name,last_name) VALUES("esteban","suasa");
INSERT INTO employees(name,last_name) VALUES("john","cena");
INSERT INTO employees(name,last_name) VALUES("carlos","restrepo");
INSERT INTO employees(name,last_name) VALUES("juanita","mastrolia");
INSERT INTO employees(name,last_name) VALUES("maximilian","pegasus");
INSERT INTO employees(name,last_name) VALUES("rosa","contreras");